package net.atos.mev.calendarcalculator;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

public class MainTest {

	private static String user = "andreu";
	private static String crTime = "2024-01-23 08:58:08.396213";
	int[][] roundStarts11Teams = { { 6, 0 }, { 6, 2 }, { 6, 4 }, { 6, 6 }, { 6, 8 }, 
			{ 14, 0 }, { 14, 2 }, { 14, 4 }, { 14, 6 }, { 14, 8 }, 
			{ 22, 0 },  
			{ 6, 11 }, { 6, 13 }, { 6, 15 }, { 6, 17 }, { 6, 19 }, 
			{ 14, 11 }, { 14, 13 }, { 14, 15 }, { 14, 17 }, { 14, 19 }, 
			{ 22, 11 }, };
	int[][] roundStarts13Teams = { { 6, 0 }, { 6, 2 }, { 6, 4 }, { 6, 6 }, { 6, 8 }, 
			{ 15, 0 }, { 15, 2 }, { 15, 4 }, { 15, 6 }, { 15, 8 }, 
			{ 24, 0 }, { 24, 2 }, { 24, 4 }, 
			{ 6, 11 }, { 6, 13 }, { 6, 15 }, { 6, 17 }, { 6, 19 }, 
			{ 15, 11 }, { 15, 13 }, { 15, 15 }, { 15, 17 }, { 15, 19 }, 
			{ 24, 11 }, { 24, 13 },	{ 24, 15 }, };
	int[][] roundStarts15Teams = { { 6, 0 }, { 6, 2 }, { 6, 4 }, { 6, 6 }, { 6, 8 }, 
			{ 16, 0 }, { 16, 2 }, { 16, 4 }, { 16, 6 }, { 16, 8 }, 
			{ 26, 0 }, { 26, 2 }, { 26, 4 }, { 26, 6 }, { 26, 8 },
			{ 6, 11 }, { 6, 13 }, { 6, 15 }, { 6, 17 }, { 6, 19 }, 
			{ 16, 11 }, { 16, 13 }, { 16, 15 }, { 16, 17 }, { 16, 19 }, 
			{ 26, 11 }, { 26, 13 }, { 26, 15 }, { 26, 17 }, { 26, 19 }, };

	public static void main(String[] args) {

		// NO SE 835b36ce-c9ba-4f27-a95a-ec105e7b2a12
		// Novice Slalom 64ae3c93-fe26-4636-88f1-7b846b790896
		// Mixed Floorball 'de004bb2-db8a-4efc-8b45-303ed8423bed'
		// Mixed Floorball bueno '9726078e-aa58-4144-9c1f-1986f9f335d2'
		// Create basic data for participant and teams
		String dob = "2000-01-03";
		String gender = "6251490e-8f99-4c4c-8c9f-10cfeeba9672";// Male
		String role = "31e0585c-a721-43c9-93f0-937fc3206b12";// Athlete
		String deleg = "f843ec32-c741-4c1b-b72d-516e45e1b78d";// Andorra
		String delegationCode = "AND";
		String teamCode = delegationCode + "-FLB-FLBTRADTEAMMIXED-2811";
		String teamName = "Floorball Mixed Andorra 1";
		String tenant = "001 TST SOEE " + delegationCode;// Test 2024 => Competition tenant
		String event = "9726078e-aa58-4144-9c1f-1986f9f335d2";// Mixed Floorball
		String entryMark = "'0'"; // or NULL
		String status = "96b65796-a34a-41a0-9d50-ee5a4f32fcd8";// Incomplete
		ParticData particData = new ParticData(dob, gender, role, tenant, event, entryMark, status, deleg);
		TeamData teamData = new TeamData(teamName, teamCode, deleg, event, tenant);

		System.out.println("+++++++++++++++++++++++++++++++++++++++");
		System.out.println("+++++++ TEAM ANDORRA FLOORBALL ++++++++");
		System.out.println("+++++++++++++++++++++++++++++++++++++++");
		generateParticipantsForTeam(101, 110, particData, teamData);
		System.out.println();
		System.out.println("+++++++++++++++++++++++++++++++++++++++");
		System.out.println("++++++ INDIVIDUAL NOVICE SLALOM +++++++");
		System.out.println("+++++++++++++++++++++++++++++++++++++++");
		event = "64ae3c93-fe26-4636-88f1-7b846b790896";// Novice Slalom
		particData = new ParticData(dob, gender, role, tenant, event, entryMark, status, deleg);
		generateParticipantsIndividual(200, 300, particData);
		// TeamData team=new TeamData("Floorball Mixed
		// Andorra",deleg+"-FLB-FLBTRADTEAMMIXED-2809",teamCode);
		// generateTeamAndParticipants();
	}

	public static void generateParticipantsIndividual(int start, int maxToGenerate, ParticData particData) {
		generateParticipants(start, maxToGenerate, particData, null);
	}

	public static void generateParticipantsForTeam(int start, int maxToGenerate, ParticData particData,
			TeamData teamData) {
		generateParticipants(start, maxToGenerate, particData, teamData);
	}

	private static void generateParticipants(int start, int maxToGenerate, ParticData particData, TeamData teamData) {
		boolean isTeam = teamData != null;
		String baseInsert = "INSERT INTO EV_REGISTER.EV_REGISTER_001_ALL (ID,PATH_PHOTO,G_01_FIRST_NAME,G_01_MIDDLE_NAME,G_01_LAST_NAME,G_01_DATE_OF_BIRTH,G_01_GENDER,G_01_EMAIL,G_01_PHONE,G_02_GROUP_DELEGATION,G_02_ROLE,G_03_CREDENTIAL_PHOTO,G_03_COUNTRY_AREA_OF_RESIDENCE,G_03_STATE_REGION_OF_RESIDENCE,G_03_CITY_OF_RESIDENCE,G_03_STREET_ADDRESS,G_03_POSTCODE,G_03_SELECT_YOUR_NATIVE_LANGUAGE,G_03_PREFERRED_SO_LANGUAGE,G_04_PARENT_GUARDIAN_FIRST_NAME,G_04_PARENT_GUARDIAN_LAST_NAME,G_04_PARENT_GUARDIAN_PHONE,G_04_PARENT_GUARDIAN_RELATIONSHIP,G_04_PARENT_GUARDIAN_COUNTRY_AREA,G_04_PARENT_GUARDIAN_PROVINCE_STATE,G_04_PARENT_GUARDIAN_CITY,G_04_PARENT_GUARDIAN_STREET_ADDRESS,G_04_PARENT_GUARDIAN_POSTCODE,G_05_EMERGENCY_CONTACT_FIRST_NAME,G_05_EMERGENCY_CONTACT_LAST_NAME,G_05_EMERGENCY_CONTACT_PHONE,G_05_EMERGENCY_CONTACT_EMAIL,G_05_RELATIONSHIP,G_06_ADDITIONAL_STAFF_ROLE,G_07_SCANNED_COPY_OF_PASSPORT_INFORMATION_PAGE,G_07_CITIZENSHIP,G_07_COUNTRY_AREA_OF_BIRTH,G_07_CITY_OF_BIRTH,G_07_PASSPORT_NUMBER,G_07_ISSUE_DATE,G_07_EXPIRY_DATE,G_07_COUNTRY_AREA_OF_PASSPORT,G_07_PASSPORT_ISSUING_AUTHORITY,G_07_COUNTRY_AREA_OF_RESIDENCE,G_07_VISA_ISSUING_PLACE,G_07_CITY_WHERE_YOU_WILL_APPLY_FOR_A_VISA,G_08_ASSOCIATED_CONDITIONS,G_08_DESCRIBE_OTHER_CONDITIONS,G_08_DOES_THIS_INDIVIDUAL_HAVE_ANY_ALLERGIES_TO_ANY_MEDICATIONS,G_08_MEDICATION_ALLERGY_DETAILS,G_08_DOES_THIS_INDIVIDUAL_HAVE_ALLERGIES_TO_INSECT_BITES_OR_STINGS,G_08_INSECT_BITES_STINGS_ALLERGY_DETAILS,G_08_DOES_THIS_INDIVIDUAL_HAVE_ANY_FOOD_ALLERGIES,G_08_FOOD_ALLERGY_DETAILS,G_08_DOES_THIS_INDIVIDUAL_HAVE_ANY_OTHER_KNOWN_ALLERGIES,G_08_OTHER_ALLERGY_DETAILS,G_08_ASSISTIVE_DEVICES,G_08_HAS_THIS_ENTRANT_EVER_HAD_AN_ABNORMAL_ELECTROCARDIOGRAM,G_08_DESCRIBE_ABNORMAL_EKG_OR_ECHO,G_08_DOES_THIS_REGISTRANT_HAVE_EPILEPSY_OR_SEIZURE_DISORDER,G_08_WHAT_IS_THE_TYPE_OF_SEIZURE_DISORDER,G_08_DOES_THIS_INDIVIDUAL_HAVE_A_VISION_IMPAIRMENT,G_08_DOES_THIS_INDIVIDUAL_HAVE_A_HEARING_IMPAIRMENT,G_08_DOES_THIS_INDIVIDUAL_HAVE_HIGH_BLOOD_PRESSURE,G_08_DOES_THIS_INDIVIDUAL_HAVE_DIABETES,G_08_DOES_THIS_INDIVIDUAL_HAVE_ASTHMA,G_08_DOES_THIS_INDIVIDUAL_HAVE_SICKLE_CELL_DISEASE,G_08_DOES_THIS_INDIVIDUAL_HAVE_EASY_BLEEDING,G_08_LIST_ALL_MEDICATION_NAMES_DOSAGES_AND_TIMES_PER_DAY,G_08_PULSE,G_08_BLOOD_PRESSURE,G_08_SPLENOMEGALY,G_09_DOES_THIS_INDIVIDUAL_HAVE_ANY_KNOWN_ALLERGIES,G_09_DOES_THIS_INDIVIDUAL_HAVE_A_LATEX_ALLERGY,G_09_LATEX_ALLERGY_DETAILS,G_09_DOES_THIS_INDIVIDUAL_HAVE_ANY_ALLERGIES_TO_ANY_MEDICATIONS,G_09_MEDICATION_ALLERGY_DETAILS,G_09_DOES_THIS_INDIVIDUAL_HAVE_ALLERGIES_TO_INSECT_BITES_OR_STINGS,G_09_INSECT_BITES_STINGS_ALLERGY_DETAILS,G_09_DOES_THIS_INDIVIDUAL_HAVE_ANY_FOOD_ALLERGIES,G_09_FOOD_ALLERGY_DETAILS,G_09_DOES_THIS_REGISTRANT_HAVE_ANY_SPECIAL_DIETARY_NEEDS,G_09_DESCRIBE_SPECIAL_DIETARY_NEEDS,G_09_DO_YOU_USE_ANY_ASSISTIVE_DEVICES,G_09_ASSISTIVE_DEVICES,G_09_DOES_THIS_REGISTRANT_HAVE_AN_ACUTE_INFECTION,G_09_DESCRIBE_ACUTE_INFECTION,G_09_DOES_THIS_REGISTRANT_HAVE_EPILEPSY_OR_SEIZURE_DISORDER,G_09_WHAT_IS_THE_TYPE_OF_SEIZURE_DISORDER,G_09_HEART_CONDITIONS,G_09_HEART_CONDITION_DETAILS,G_09_DOES_THIS_INDIVIDUAL_HAVE_A_MENTAL_HEALTH_CONDITION,G_09_MENTAL_HEALTH_CONDITION_DETAILS,G_09_DOES_THIS_INDIVIDUAL_HAVE_ANY_MISSING_ORGANS,G_09_MISSING_ORGAN_DETAILS,G_09_DOES_THIS_INDIVIDUAL_HAVE_A_CHRONIC_INFECTION,G_09_CHRONIC_INFECTION_DETAILS,G_09_DOES_THIS_INDIVIDUAL_HAVE_HIGH_BLOOD_PRESSURE,G_09_DOES_THIS_INDIVIDUAL_HAVE_DIABETES,G_09_DOES_THIS_INDIVIDUAL_HAVE_ASTHMA,G_09_DOES_THIS_INDIVIDUAL_HAVE_SICKLE_CELL_DISEASE,G_09_DOES_THIS_INDIVIDUAL_HAVE_A_SICKLE_CELL_TRAIT,G_09_DOES_THIS_INDIVIDUAL_HAVE_EASY_BLEEDING,G_09_ADDITIONAL_HEALTH_INFORMATION,G_09_DOES_THIS_INDIVIDUAL_TAKE_ANY_MEDICATIONS,G_09_LIST_ALL_MEDICATION_NAMES_DOSAGES_AND_TIMES_PER_DAY,G_09_IS_THIS_REGISTRANT_ABLE_TO_ADMINISTER_THEIR_OWN_MEDICATIONS,G_10_MEDICAL_DEGREE_TYPE,G_10_YEAR_YOU_RECEIVED_YOUR_MEDICAL_DEGREE,G_10_CLINICAL_FOCUS_HEALTH_CARE_PROFESSION,G_10_MEDICAL_LICENSE_NUMBER,G_10_REGULATORY_AUTHORITY_THAT_GRANTED_YOUR_LICENSE,G_10_LICENSE_DATE,G_10_LICENSE_EXPIRY,G_10_NAME_OF_YOUR_EMPLOYER_ORGANIZATION,G_10_TYPE_OF_EMPLOYER_ORGANIZATION,G_10_OTHER_TYPE_OF_EMPLOYER_ORGANISATION,G_10_PLEASE_UPLOAD_YOUR_MEDICAL_LICENSE,G_10_PLEASE_UPLOAD_YOUR_LATEST_CV_RESUME,G_10_PLEASE_UPLOAD_HOD_SIGNED_DELEGATION_MEDICAL_STAFF_LETTER,G_11_SPORT,G_12_ACCOMMODATION,G_13_ACCOMMODATION,G_15_RELEASE_FORM,G_15_LIKENESS_RELEASE_FORM,G_16_HAVE_YOU_COMPLETED_THE_HOD_READINESS_TRAINING,G_17_HAVE_YOU_COMPLETED_THE_WORLD_GAMES_COACH_PREPARATION_MODULE,G_17_IF_YOU_ARE_COACHING_A_UNIFIED_TEAM_HAVE_YOU_COMPLETED_THE_UNIFIED_SPORTS_COACHING_TRAINING,G_18_REGISTRATION_NOTES,G_18_VISA_INVITATIONAL_LETTER_SENT,G_19_CONFIRMED_TICKET_INVOICE,G_19_NUMBER_OF_SUITCASES_LUGGAGE,G_19_NUMBER_OF_SPORTS_EQUIPMENT,G_19_NUMBER_OF_INDIVIDUALS_USING_MOBILITY_ASSISTANCE_DEVICES,G_19_TRANSIT_TO_MOSCOW,G_19_METHOD_OF_ARRIVAL,G_19_DEPARTING_CITY,G_19_DEPARTING_COUNTRY,G_19_AIRPORT_OF_ARRIVAL,G_19_RAILWAY_STATION_OF_ARRIVAL,G_19_ARRIVAL_TRAIN_FLIGHT_NUMBER,G_19_ARRIVAL_RAILWAY_CAR_NUMBER,G_19_ARRIVAL_DATE,G_19_ARRIVAL_TIME,G_19_TRANSIT_FROM_MOSCOW,G_19_METHOD_OF_DEPARTURE,G_19_DESTINATION_CITY,G_19_DESTINATION_COUNTRY,G_19_AIRPORT_OF_DEPARTURE,G_19_RAILWAY_STATION_OF_DEPARTURE,G_19_DEPARTURE_TRAIN_FLIGHT_NUMBER,G_19_DEPARTURE_FROM_MOSCOW_RAILWAY_CAR_NUMBER,G_19_DEPARTURE_DATE,G_19_DEPARTURE_TIME,PEOPLE_ID,REGISTRATION_STATUS_ID,TENANT_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE,G_11_CATEGORY,G_20_IS_DATA_CONFIRMED,G_07_REQUIRES_VISA_TO_ENTER_ITALY,G08_DEGREE_OF_DISABILITY,G08_OTHER_ASSOCIATED_CONDITIONS,G08_IS_WHEELCHAIR_USER,G08_OTHER_MOBILITY_DEVICES,G08_COMMUNICATIONS_ACCOMODATIONS,G08_MEDICAL_DEVICES,G08_OTHER_ASSISTIVE_DEVICES_AND_ACCOMODATIONS,G08_HAS_CARDIAC_CONDITION,G08_HAS_KIDNEY_DISEASE,G08_HAS_ANEMIA,G08_HAS_HEATILLNESS,G08_HAS_COELIAC_DISEASE,G08_HAS_OSTEOPOROSIS,G08_IS_NON_VERBAL,G08_EVER_HAD_HEAD_INJURY_OR_CONCUSSION,G08_HAS_ANY_RELATIVE_DIED_OF_HEART_PROBLEMS_OR_SUDDEN_DEATH_BEFORE_AGE50,G08_HAS_MISSING_ORGAN,G08_HAD_COVID19,G08_HAVE_BEEN_IMMUNIZED_FOR_COVID19,G08_ALLERGIES_LIST,G08_HAD_SURGURIES,G08_SURGURIES_DETAILS,G08_HAS_DOCTOR_LIMITED_PARTICIPATION_IN_SPORTS,G08_DOCTOR_LIMITED_PARTICIPATION_IN_SPORTS_DETAILS,G08_HAD_BROKEN_BONES_OR_DISLOCATED_JOINTS,G08_BROKEN_BONES_OR_DISLOCATED_JOINTS_DETAILS,G08_HAS_LIVER_DISEASE,G08_LIVER_DISEASE_DETAILS,G08_HAS_LUNG_DISEASE,G08_LUNG_DISEASE_DETAILS,G08_HAS_HEART_DISEASE,G08_HEART_DISEASE_DETAILS,G08_HAS_BEHAVIORAL_MENTAL_HEALTH_SENSORY_CONDITIONS,G08_BEHAVIORAL_MENTAL_HEALTH_SENSORY_CONDITIONS_DETAILS,G08_HEIGHT,G08_WEIGHT,G08_BLOOD_PRESSURE_DIASTOLIC,G08_VISION_OS,G08_VISION_OD,G08_EYES_EARS_NOSE_THROAT,G08_EYES_EARS_NOSE_THROAT_FINDINGS,G08_HEART,G08_HEART_FINDINGS,G08_LUNGS,G08_LUNGS_FINDINGS,G08_ABDOMEN,G08_ABDOMEN_FINDINGS,G08_SKIN,G08_SKIN_FINDINGS,G08_NEUROLOGICAL,G08_NEUROLOGICAL_FINDINGS,G08_NECK,G08_NECK_FINDINGS,G08_BACK,G08_BACK_FINDINGS,G08_SHOULDER_AND_ARM,G08_SHOULDER_AND_ARM_FINDINGS,G08_ELBOW_AND_FOREARM,G08_ELBOW_AND_FOREARM_FINDINGS,G08_WRIST_HAND_FINGERS,G08_WRIST_HAND_FINGERS_FINDINGS,G08_HIP_AND_THIGH,G08_HIP_AND_THIGH_FINDINGS,G08_KNEE,G08_KNEE_FINDINGS,G08_LOWER_LEG_AND_ANKLE,G08_LOWER_LEG_AND_ANKLE_FINDINGS,G08_FOOT_AND_TOES,G08_FOOT_AND_TOES_FINDINGS,G08_MEDICAL_ELIGIBILITY,G08_ADDITIONAL_DETAILS,G14_ARE_YOU_CURRENTLY_A_STUDENT,G14_FULL_NAME_OF_YOUR_SCHOOL,G14_CURRENT_LEVEL_OF_SCHOOLING,G14_LEVEL_OF_SCHOOLING_COMPLETED,G14_ARE_YOU_EMPLOYED,G14_HOURS_PER_WEEK_WORKED,G14_NAME_OF_THE_COMPANY,G14_JOB_DESCRIPTION,G14_DURATION_OF_EMPLOYMENT,G14_SELECTED_BIOGRAPHY_QUESTION,G14_BIOGRAPHY_ANSWER,G_19_AIRPORT_TRAIN_BUS_STATION_OF_ARRIVAL,G_19_AIRPORT_TRAIN_BUS_STATION_OF_DEPARTURE,G_08_MEDICAL_FORM_UPLOAD,G_08_DOES_THIS_REGISTRANT_HAVE_ANY_SPECIAL_DIETARY_NEEDS,G_08_DESCRIBE_SPECIAL_DIETARY_NEEDS,G_08_CONCUSSION_NO_IN_LIFETIME,G_08_OCCURRENCE_OF_LAST_CONCUSSION,G_09_ASSOCIATED_CONDITIONS,G_09_OTHER_ASSOCIATED_CONDITIONS,G_09_IS_WHEELCHAIR_USER,G_09_COMMUNICATIONS_ACCOMODATIONS,G_09_MEDICAL_DEVICES,G_09_OTHER_ASSISTIVE_DEVICES_AND_ACCOMODATIONS,G_09_EVER_HAD_HEAD_INJURY_OR_CONCUSSION,G_09_CONCUSSION_NO_IN_LIFETIME,G_09_OCCURRENCE_OF_LAST_CONCUSSION,G_09_DOES_THIS_INDIVIDUAL_HAVE_A_VISION_IMPAIRMENT,G_09_DOES_THIS_INDIVIDUAL_HAVE_A_HEARING_IMPAIRMENT,G_09_HAS_DOCTOR_LIMITED_PARTICIPATION_IN_SPORTS,G_09_ALLERGIES_LIST,G_09_OTHER_ALLERGY_DETAILS,G_09_OTHER_MOBILITY_DEVICES,G_07_IDENTIFICATION_DOCUMENT,G_19_TYPE_OF_LUGGAGE) VALUES ";
		String uuid = "";
		String replaceMent = "";
		String suffix = "";
		int suffixSize = 4;
		String teamId = "";
		if (isTeam) {
			teamId = createTeam(crTime, user, teamData);
			teamData.setTeamId(teamId);
		}
		Set<String> participantsTeam = new HashSet<>();
		Set<String> indivInscriptions = new HashSet<>();
		System.out.println(baseInsert);
		for (int i = start; i <= maxToGenerate; i++) {
			if (i != start) {
				System.out.print(",");
			}
			String partial = "0000" + i;
			uuid = UUID.randomUUID().toString();
			suffix = partial.substring(partial.length() - suffixSize, partial.length());

			replaceMent = "('" + uuid + "',NULL,'Primer" + suffix + "',NULL,'Importado','" + particData.getDob() + "','"
					+ particData.getGender() + "','primero" + suffix + "@mailinator.com',NULL,'" + teamData.getDeleg()
					+ "','" + particData.getRole()
					+ "',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'"
					+ particData.getEvent()
					+ "',NULL,NULL,NULL,NULL,false,false,false,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'"
					+ particData.getStatus() + "','" + particData.getTenant() + "','" + user + "','" + crTime + "','"
					+ user + "','" + crTime
					+ "',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)";
			System.out.println(replaceMent);
			if (isTeam) {
				participantsTeam.add(uuid);
			} else {
				indivInscriptions.add(uuid);
			}
		}
		System.out.println();
		if (isTeam) {
			printParticipantMembers(participantsTeam, particData, teamData, user, crTime);
		} else {
			printIndividualInscriptions(indivInscriptions, particData, user, crTime);
		}
	}

	private static void printIndividualInscriptions(Set<String> indivInscriptions, ParticData partic, String user,
			String crTime) {
		boolean isFirst = true;
		String baseInsert = "INSERT INTO EV_COMPETITION.EV_DISC_EVENT_PARTICIPANTS (ID,ORGANISATION_CODE,REGISTER_ID,IS_TEAM,BIB,ENTRY_MARK,TEAM_CODE,DISC_EVENTS_ID,PARTICIPANT_STATUS_ID,TENANT_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE,TEAM_NAME,SHORT_NAME,TEAM_COLOR,TEAM_NUMBER,DISC_EVENTS_LEVEL_ID) VALUES ";
		System.out.println(baseInsert);
		for (String partId : indivInscriptions) {
			String aId = UUID.randomUUID().toString();
			if (!isFirst) {
				System.out.print(",");
			}
			String dataInsert = "('" + aId + "','" + partic.getDeleg() + "','" + partId + "',false,NULL,"
					+ partic.getEntryMark() + ",NULL,'" + partic.getEvent() + "',NULL,'" + partic.getTenant() + "','"
					+ user + "','" + crTime + "','" + user + "','" + crTime + "',NULL,NULL,NULL,NULL,NULL)";
			System.out.println(dataInsert);
			isFirst = false;
		}
	}

	private static void printParticipantMembers(Set<String> participantsTeam, ParticData partic, TeamData team,
			String user, String crTime) {
		boolean isFirst = true;
		String baseInsert = "INSERT INTO EV_COMPETITION.EV_DISC_EVENT_PARTICIPANTS_MEMBERS (ID,ORGANISATION_CODE,REGISTER_ID,PARTICIPANT_ROLE,BIB,ENTRY_MARK,PARTICIPANT_ID,TENANT_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE,FIRST_NAME,LAST_NAME) VALUES ";
		System.out.println(baseInsert);
		for (String partId : participantsTeam) {
			String aId = UUID.randomUUID().toString();
			if (!isFirst) {
				System.out.print(",");
			}
			String dataInsert = "('" + aId + "','" + team.getDeleg() + "','" + partId + "','" + partic.getRole()
					+ "',NULL,NULL,'" + team.getTeamId() + "','" + partic.getTenant() + "','" + user + "','" + crTime
					+ "','" + user + "','" + crTime + "',NULL,NULL)";
			System.out.println(dataInsert);
			isFirst = false;
		}
	}

	private static String createTeam(String crTime, String user, TeamData team) {
		String uuid = UUID.randomUUID().toString();
		String baseInsert = "INSERT INTO EV_COMPETITION.EV_DISC_EVENT_PARTICIPANTS (ID,ORGANISATION_CODE,REGISTER_ID,IS_TEAM,BIB,ENTRY_MARK,TEAM_CODE,DISC_EVENTS_ID,PARTICIPANT_STATUS_ID,TENANT_ID,CREATED_BY,CREATED_DATE,LAST_MODIFIED_BY,LAST_MODIFIED_DATE,TEAM_NAME,SHORT_NAME,TEAM_COLOR,TEAM_NUMBER,DISC_EVENTS_LEVEL_ID) VALUES ";
		String dataInsert = "('" + uuid + "','" + team.getDeleg() + "',NULL,true,NULL,0,'" + team.getTeamCode() + "','"
				+ team.getEvent() + "',NULL,'" + team.getTenant() + "','" + user + "','" + crTime + "','" + user + "','"
				+ crTime + "','" + team.getTeamName() + "',NULL,NULL,NULL,NULL)";
		System.out.println(baseInsert + dataInsert);
		System.out.println();
		return uuid;
	}

}
